##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.18.0-B7] date: [Thu Feb 23 16:00:59 PST 2023]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = tls-server


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES :=  
C_SOURCES += app/main.c
C_SOURCES += app/stm32h7xx_it.c
C_SOURCES += app/stm32h7xx_hal_msp.c
C_SOURCES += app/stm32h7xx_hal_timebase_tim.c
C_SOURCES += app/syscalls.c
C_SOURCES += app/sysmem.c
C_SOURCES += source/app_ethernet/app_ethernet.c
C_SOURCES += source/ethernetif/ethernetif.c
C_SOURCES += source/tcp_echoserver/tcp_echoserver.c
C_SOURCES += source/wolfssl_example/wolfssl_example.c
C_SOURCES += source/tls_server/tls_server.c
C_SOURCES += Drivers/BSP/Components/lan8742/lan8742.c
C_SOURCES += Drivers/BSP/STM32H7xx_Nucleo/stm32h7xx_nucleo.c
C_SOURCES += Drivers/CMSIS/Device/ST/STM32H7xx/system_stm32h7xx.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc.c 
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc_ex.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cortex.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_eth.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_eth_ex.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_exti.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash_ex.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_gpio.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c_ex.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr_ex.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc_ex.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim_ex.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart_ex.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rng.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rng_ex.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rtc.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rtc_ex.c
C_SOURCES += external/FreeRTOS/Source/croutine.c
C_SOURCES += external/FreeRTOS/Source/event_groups.c
C_SOURCES += external/FreeRTOS/Source/list.c
C_SOURCES += external/FreeRTOS/Source/queue.c
C_SOURCES += external/FreeRTOS/Source/tasks.c
C_SOURCES += external/FreeRTOS/Source/timers.c 
C_SOURCES += external/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c
C_SOURCES += external/FreeRTOS/Source/portable/MemMang/heap_4.c
C_SOURCES += external/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c 
C_SOURCES += external/wolfssl/wolfcrypt/test/test.c
C_SOURCES += external/wolfssl/wolfcrypt/benchmark/benchmark.c
C_SOURCES += external/LwIP/src/api/api_lib.c
C_SOURCES += external/LwIP/src/api/api_msg.c
C_SOURCES += external/LwIP/src/api/err.c
C_SOURCES += external/LwIP/src/api/netbuf.c
C_SOURCES += external/LwIP/src/api/netdb.c
C_SOURCES += external/LwIP/src/api/netifapi.c
C_SOURCES += external/LwIP/src/api/sockets.c
C_SOURCES += external/LwIP/src/api/tcpip.c
C_SOURCES += external/LwIP/src/apps/http/fs.c
C_SOURCES += external/LwIP/src/core/ipv4/autoip.c
C_SOURCES += external/LwIP/src/core/ipv4/dhcp.c
C_SOURCES += external/LwIP/src/core/ipv4/etharp.c
C_SOURCES += external/LwIP/src/core/ipv4/icmp.c
C_SOURCES += external/LwIP/src/core/ipv4/igmp.c
C_SOURCES += external/LwIP/src/core/ipv4/ip4.c
C_SOURCES += external/LwIP/src/core/ipv4/ip4_addr.c
C_SOURCES += external/LwIP/src/core/ipv4/ip4_frag.c
C_SOURCES += external/LwIP/src/core/def.c
C_SOURCES += external/LwIP/src/core/dns.c
C_SOURCES += external/LwIP/src/core/inet_chksum.c
C_SOURCES += external/LwIP/src/core/init.c
C_SOURCES += external/LwIP/src/core/ip.c
C_SOURCES += external/LwIP/src/core/mem.c
C_SOURCES += external/LwIP/src/core/memp.c
C_SOURCES += external/LwIP/src/core/netif.c
C_SOURCES += external/LwIP/src/core/pbuf.c
C_SOURCES += external/LwIP/src/core/raw.c
C_SOURCES += external/LwIP/src/core/stats.c
C_SOURCES += external/LwIP/src/core/sys.c
C_SOURCES += external/LwIP/src/core/tcp.c
C_SOURCES += external/LwIP/src/core/tcp_in.c
C_SOURCES += external/LwIP/src/core/tcp_out.c
C_SOURCES += external/LwIP/src/core/timeouts.c
C_SOURCES += external/LwIP/src/core/udp.c
C_SOURCES += external/LwIP/src/netif/ethernet.c
C_SOURCES += external/LwIP/system/OS/sys_arch.c
C_SOURCES += external/wolfssl/wolfcrypt/src/aes.c
C_SOURCES += external/wolfssl/wolfcrypt/src/arc4.c
C_SOURCES += external/wolfssl/wolfcrypt/src/port/arm/armv8-32-curve25519_c.c
C_SOURCES += external/wolfssl/wolfcrypt/src/port/arm/armv8-32-sha512-asm_c.c
C_SOURCES += external/wolfssl/wolfcrypt/src/port/arm/armv8-aes.c
C_SOURCES += external/wolfssl/wolfcrypt/src/port/arm/armv8-chacha.c
C_SOURCES += external/wolfssl/wolfcrypt/src/port/arm/armv8-curve25519_c.c
C_SOURCES += external/wolfssl/wolfcrypt/src/port/arm/armv8-poly1305.c
C_SOURCES += external/wolfssl/wolfcrypt/src/port/arm/armv8-sha256.c
C_SOURCES += external/wolfssl/wolfcrypt/src/port/arm/armv8-sha512.c
C_SOURCES += external/wolfssl/wolfcrypt/src/asm.c
C_SOURCES += external/wolfssl/wolfcrypt/src/asn.c
C_SOURCES += external/wolfssl/wolfcrypt/src/port/atmel/atmel.c
C_SOURCES += external/wolfssl/wolfcrypt/src/blake2b.c
C_SOURCES += external/wolfssl/wolfcrypt/src/blake2s.c
C_SOURCES += external/wolfssl/wolfcrypt/src/camellia.c
C_SOURCES += external/wolfssl/wolfcrypt/src/chacha.c
C_SOURCES += external/wolfssl/wolfcrypt/src/chacha20_poly1305.c
C_SOURCES += external/wolfssl/wolfcrypt/src/cmac.c
C_SOURCES += external/wolfssl/wolfcrypt/src/coding.c
C_SOURCES += external/wolfssl/wolfcrypt/src/compress.c
C_SOURCES += external/wolfssl/wolfcrypt/src/cpuid.c
C_SOURCES += external/wolfssl/wolfcrypt/src/curve25519.c
C_SOURCES += external/wolfssl/wolfcrypt/src/curve448.c
C_SOURCES += external/wolfssl/wolfcrypt/src/des3.c
C_SOURCES += external/wolfssl/wolfcrypt/src/dh.c
C_SOURCES += external/wolfssl/wolfcrypt/src/dsa.c
C_SOURCES += external/wolfssl/wolfcrypt/src/ecc.c
C_SOURCES += external/wolfssl/wolfcrypt/src/ecc_fp.c
C_SOURCES += external/wolfssl/wolfcrypt/src/eccsi.c
C_SOURCES += external/wolfssl/wolfcrypt/src/ed25519.c
C_SOURCES += external/wolfssl/wolfcrypt/src/ed448.c
C_SOURCES += external/wolfssl/wolfcrypt/src/error.c
C_SOURCES += external/wolfssl/wolfcrypt/src/evp.c
C_SOURCES += external/wolfssl/wolfcrypt/src/fe_448.c
C_SOURCES += external/wolfssl/wolfcrypt/src/fe_low_mem.c
C_SOURCES += external/wolfssl/wolfcrypt/src/fe_operations.c
C_SOURCES += external/wolfssl/wolfcrypt/src/ge_448.c
C_SOURCES += external/wolfssl/wolfcrypt/src/ge_low_mem.c
C_SOURCES += external/wolfssl/wolfcrypt/src/ge_operations.c
C_SOURCES += external/wolfssl/wolfcrypt/src/hash.c
C_SOURCES += external/wolfssl/wolfcrypt/src/hmac.c
C_SOURCES += external/wolfssl/wolfcrypt/src/integer.c
C_SOURCES += external/wolfssl/wolfcrypt/src/kdf.c
C_SOURCES += external/wolfssl/wolfcrypt/src/logging.c
C_SOURCES += external/wolfssl/wolfcrypt/src/md2.c
C_SOURCES += external/wolfssl/wolfcrypt/src/md4.c
C_SOURCES += external/wolfssl/wolfcrypt/src/md5.c
C_SOURCES += external/wolfssl/wolfcrypt/src/memory.c
C_SOURCES += external/wolfssl/wolfcrypt/src/misc.c
C_SOURCES += external/wolfssl/wolfcrypt/src/pkcs12.c
C_SOURCES += external/wolfssl/wolfcrypt/src/pkcs7.c
C_SOURCES += external/wolfssl/wolfcrypt/src/poly1305.c
C_SOURCES += external/wolfssl/wolfcrypt/src/pwdbased.c
C_SOURCES += external/wolfssl/wolfcrypt/src/random.c
C_SOURCES += external/wolfssl/wolfcrypt/src/rc2.c
C_SOURCES += external/wolfssl/wolfcrypt/src/ripemd.c
C_SOURCES += external/wolfssl/wolfcrypt/src/rsa.c
C_SOURCES += external/wolfssl/wolfcrypt/src/sakke.c
C_SOURCES += external/wolfssl/wolfcrypt/src/sha.c
C_SOURCES += external/wolfssl/wolfcrypt/src/sha256.c
C_SOURCES += external/wolfssl/wolfcrypt/src/sha3.c
C_SOURCES += external/wolfssl/wolfcrypt/src/sha512.c
C_SOURCES += external/wolfssl/wolfcrypt/src/signature.c
C_SOURCES += external/wolfssl/wolfcrypt/src/sp_arm32.c
C_SOURCES += external/wolfssl/wolfcrypt/src/sp_arm64.c
C_SOURCES += external/wolfssl/wolfcrypt/src/sp_armthumb.c
C_SOURCES += external/wolfssl/wolfcrypt/src/sp_c32.c
C_SOURCES += external/wolfssl/wolfcrypt/src/sp_c64.c
C_SOURCES += external/wolfssl/wolfcrypt/src/sp_cortexm.c
C_SOURCES += external/wolfssl/wolfcrypt/src/sp_dsp32.c
C_SOURCES += external/wolfssl/wolfcrypt/src/sp_int.c
C_SOURCES += external/wolfssl/wolfcrypt/src/sp_x86_64.c
C_SOURCES += external/wolfssl/wolfcrypt/src/srp.c
C_SOURCES += external/wolfssl/wolfcrypt/src/port/st/stm32.c
C_SOURCES += external/wolfssl/wolfcrypt/src/port/st/stsafe.c
C_SOURCES += external/wolfssl/wolfcrypt/src/tfm.c
C_SOURCES += external/wolfssl/wolfcrypt/src/wc_dsp.c
C_SOURCES += external/wolfssl/wolfcrypt/src/wc_encrypt.c
C_SOURCES += external/wolfssl/wolfcrypt/src/wc_pkcs11.c
C_SOURCES += external/wolfssl/wolfcrypt/src/wc_port.c
C_SOURCES += external/wolfssl/wolfcrypt/src/wolfevent.c
C_SOURCES += external/wolfssl/wolfcrypt/src/wolfmath.c 
C_SOURCES += external/wolfssl/src/bio.c
C_SOURCES += external/wolfssl/src/conf.c
C_SOURCES += external/wolfssl/src/crl.c
C_SOURCES += external/wolfssl/src/dtls.c
C_SOURCES += external/wolfssl/src/dtls13.c
C_SOURCES += external/wolfssl/src/internal.c
C_SOURCES += external/wolfssl/src/keys.c
C_SOURCES += external/wolfssl/src/ocsp.c
C_SOURCES += external/wolfssl/src/pk.c
C_SOURCES += external/wolfssl/src/quic.c
C_SOURCES += external/wolfssl/src/sniffer.c
C_SOURCES += external/wolfssl/src/ssl.c
C_SOURCES += external/wolfssl/src/tls.c
C_SOURCES += external/wolfssl/src/tls13.c
C_SOURCES += external/wolfssl/src/wolfio.c
C_SOURCES += external/wolfssl/src/x509.c
C_SOURCES += external/wolfssl/src/x509_str.c

# ASM sources
ASM_SOURCES :=
ASM_SOURCES += startup_stm32h723xx.s

# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES :=
C_INCLUDES += -Iapp
C_INCLUDES += -Iconfig
C_INCLUDES += -Isource/app_ethernet/
C_INCLUDES += -Isource/ethernetif/
C_INCLUDES += -Isource/tcp_echoserver
C_INCLUDES += -Isource/tls_server
C_INCLUDES += -Isource/wolfssl_example
C_INCLUDES += -IDrivers/BSP/Components/lan8742
C_INCLUDES += -IDrivers/BSP/Components/Common
C_INCLUDES += -IDrivers/BSP/STM32H7xx_Nucleo
C_INCLUDES += -IDrivers/STM32H7xx_HAL_Driver/Inc
C_INCLUDES += -IDrivers/STM32H7xx_HAL_Driver/Inc/Legacy
C_INCLUDES += -IDrivers/CMSIS/Device/ST/STM32H7xx/Include
C_INCLUDES += -IDrivers/CMSIS/Include
C_INCLUDES += -Iexternal/LwIP/system
C_INCLUDES += -Iexternal/LwIP/src/include
C_INCLUDES += -Iexternal/wolfssl/
C_INCLUDES += -Iexternal/LwIP/src/include/compat/posix
C_INCLUDES += -Iexternal/LwIP/src/include/compat/posix
C_INCLUDES += -Iexternal/FreeRTOS/Source/include
C_INCLUDES += -Iexternal/FreeRTOS/Source/CMSIS_RTOS_V2 
C_INCLUDES += -Iexternal/FreeRTOS/Source/CMSIS_RTOS_V2
C_INCLUDES += -Iexternal/FreeRTOS/Source/portable/GCC/ARM_CM4F

#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-

CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S

#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m7

# fpu
FPU = -mfpu=fpv5-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS := 
C_DEFS += -DUSE_HAL_DRIVER
C_DEFS += -DSTM32H723xx
C_DEFS += -DDEBUG
C_DEFS += -DWOLFSSL_USER_SETTINGS
C_DEFS += -DFREERTOS

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32H723ZGTx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***