##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.18.0-B7] date: [Thu Feb 23 16:00:59 PST 2023]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = tls-server


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES :=  
C_SOURCES += app/main.c
C_SOURCES += app/stm32h7xx_it.c
C_SOURCES += app/stm32h7xx_hal_msp.c
C_SOURCES += app/syscalls.c
C_SOURCES += app/sysmem.c
C_SOURCES += source/app_ethernet/app_ethernet.c
C_SOURCES += source/ethernetif/ethernetif.c
C_SOURCES += source/tcp_echoserver/tcp_echoserver.c
C_SOURCES += Drivers/BSP/Components/lan8742/lan8742.c
C_SOURCES += Drivers/BSP/STM32H7xx_Nucleo/stm32h7xx_nucleo.c
C_SOURCES += Drivers/CMSIS/Device/ST/STM32H7xx/system_stm32h7xx.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc.c 
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc_ex.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cortex.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_eth.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_eth_ex.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_exti.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash_ex.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_gpio.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c_ex.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr_ex.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc_ex.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim_ex.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart.c
C_SOURCES += Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart_ex.c 
C_SOURCES += external/LwIP/src/api/api_lib.c
C_SOURCES += external/LwIP/src/api/api_msg.c
C_SOURCES += external/LwIP/src/api/err.c
C_SOURCES += external/LwIP/src/api/netbuf.c
C_SOURCES += external/LwIP/src/api/netdb.c
C_SOURCES += external/LwIP/src/api/netifapi.c
C_SOURCES += external/LwIP/src/api/sockets.c
C_SOURCES += external/LwIP/src/api/tcpip.c
C_SOURCES += external/LwIP/src/apps/http/fs.c
C_SOURCES += external/LwIP/src/core/ipv4/autoip.c
C_SOURCES += external/LwIP/src/core/ipv4/dhcp.c
C_SOURCES += external/LwIP/src/core/ipv4/etharp.c
C_SOURCES += external/LwIP/src/core/ipv4/icmp.c
C_SOURCES += external/LwIP/src/core/ipv4/igmp.c
C_SOURCES += external/LwIP/src/core/ipv4/ip4.c
C_SOURCES += external/LwIP/src/core/ipv4/ip4_addr.c
C_SOURCES += external/LwIP/src/core/ipv4/ip4_frag.c
C_SOURCES += external/LwIP/src/core/def.c
C_SOURCES += external/LwIP/src/core/dns.c
C_SOURCES += external/LwIP/src/core/inet_chksum.c
C_SOURCES += external/LwIP/src/core/init.c
C_SOURCES += external/LwIP/src/core/ip.c
C_SOURCES += external/LwIP/src/core/mem.c
C_SOURCES += external/LwIP/src/core/memp.c
C_SOURCES += external/LwIP/src/core/netif.c
C_SOURCES += external/LwIP/src/core/pbuf.c
C_SOURCES += external/LwIP/src/core/raw.c
C_SOURCES += external/LwIP/src/core/stats.c
C_SOURCES += external/LwIP/src/core/sys.c
C_SOURCES += external/LwIP/src/core/tcp.c
C_SOURCES += external/LwIP/src/core/tcp_in.c
C_SOURCES += external/LwIP/src/core/tcp_out.c
C_SOURCES += external/LwIP/src/core/timeouts.c
C_SOURCES += external/LwIP/src/core/udp.c
C_SOURCES += external/LwIP/src/netif/ethernet.c
C_SOURCES += external/LwIP/system/OS/sys_arch.c 

# ASM sources
ASM_SOURCES :=
ASM_SOURCES += startup_stm32h723xx.s

# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES :=
C_INCLUDES += -Iapp
C_INCLUDES += -Iconfig
C_INCLUDES += -Isource/app_ethernet/
C_INCLUDES += -Isource/ethernetif/
C_INCLUDES += -Isource/tcp_echoserver
C_INCLUDES += -IDrivers/BSP/Components/lan8742
C_INCLUDES += -IDrivers/BSP/Components/Common
C_INCLUDES += -IDrivers/BSP/STM32H7xx_Nucleo
C_INCLUDES += -IDrivers/STM32H7xx_HAL_Driver/Inc
C_INCLUDES += -IDrivers/STM32H7xx_HAL_Driver/Inc/Legacy
C_INCLUDES += -IDrivers/CMSIS/Device/ST/STM32H7xx/Include
C_INCLUDES += -IDrivers/CMSIS/Include
C_INCLUDES += -Iexternal/LwIP/system
C_INCLUDES += -Iexternal/LwIP/src/include

#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m7

# fpu
FPU = -mfpu=fpv5-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS := 
C_DEFS += -DUSE_HAL_DRIVER
C_DEFS += -DSTM32H723xx
C_DEFS += -DDEBUG

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32H723ZGTx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***